# Generated by Django 6.0.5 on 2026-05-23 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('edad', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceplan')),
            ],
        ),
    ]
