# Generated by Django 5.2.1 on 2026-05-23 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('es_red', models.BooleanField(default=True)),
                ('distancia_km', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('calificacion', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('deducible_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuera_de_red_multiplicador', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_visita', models.CharField(choices=[('medico_general', 'Médico General'), ('especialista', 'Especialista'), ('urgencias', 'Urgencias'), ('laboratorios', 'Laboratorios')], default='especialista', max_length=20)),
                ('urgencia', models.CharField(default='media', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CopaymentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_visita', models.CharField(choices=[('medico_general', 'Médico General'), ('especialista', 'Especialista'), ('urgencias', 'Urgencias'), ('laboratorios', 'Laboratorios')], max_length=20)),
                ('monto_deducible_cumplido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_deducible_no_cumplido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copagos', to='insurance.insuranceplan')),
            ],
            options={
                'unique_together': {('plan', 'tipo_visita')},
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='insurance.hospital')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.specialty')),
            ],
            options={
                'unique_together': {('hospital', 'specialty')},
            },
        ),
    ]
